#  This plugin was made by: Bermuda with help from Van Stein & Groentjes

racecommand:


races:


classes:


profile:
  race:
  classes:
  seperaterank:
  seperateusername:
  rankandusername:
  level:
  exp:
  maxhp:
  spec: