# This plugin is made/developed by Bermuda and Van Stein & Groentjes.
factions:
  Alliance: ''
  Horde: ''
characteristics:
  strength: 1
  dexterity: 1
  constitution: 1
  intelligence: 1
  wisdom: 1
  charisma: 1
  luck: 1
onjoin:
  OnFirstJoinMessageEnable: true
  OnReturningJoinMessageEnable: true
  AddPointsOnRaceSelect: 6

GuiOrChat:
  Profile: 'gui'
  Class: 'gui'
  Race: 'gui'